# Generated by Django 2.1.8 on 2020-05-11 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daohang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='导航条')),
            ],
            options={
                'verbose_name': '导航条',
                'verbose_name_plural': '导航条',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='url'),
            preserve_default=False,
        ),
    ]
