# Generated by Django 2.1.8 on 2020-05-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200511_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link_url',
            field=models.URLField(max_length=255, verbose_name='图片链接'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_info',
            field=models.CharField(default='', max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='comment_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='linkurl',
            field=models.URLField(max_length=255, verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=255, verbose_name='链接名称'),
        ),
    ]
