# Generated by Django 2.1.8 on 2020-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200511_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sort2_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='类别'),
        ),
    ]
